### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by HairyHook** [Lacro59/playnite-gameactivity-plugin#126]
[GameActivity_2022-03-12.zip](https://github.com/Lacro59/playnite-gameactivity-plugin/files/8238649/GameActivity_2022-03-12.zip)
Playnite error message right after game session. Attaching logs.

**Comment by BanCrash** [comment]
This seems to be caused by my temporary workaround. I assume you have installed PlayState, right?

Could you share also the PlayState.txt file placed inside "C:\Users\User\AppData\Roaming\Playnite\ExtensionsData"? If it wasn't reused after the error.

**Comment by HairyHook** [comment]
> This seems to be caused by my temporary workaround. I assume you have installed PlayState, right?
> 
> Could you share also the PlayState.txt file placed inside "C:\Users\User\AppData\Roaming\Playnite\ExtensionsData"? If it wasn't reused after the error.
> 
> EDIT: Nevermind, it seems that this error is caused when the PlayState.txt file is cleaned. I will open a PR for fixing this.
> 
> EDIT2: Well, could you confirm that your bug is that your PlayState.txt is empty? I don't see any reason to having your PlayState.txt empty since you didn't execute another game after.

Thanks for your reply. Yes, I had PlayState installed and the .txt file is indeed empty. I have uninstalled PlayState and the same "Input string was not in a correct format" message pops.

**Comment by BanCrash** [comment]
Hi @HairyHook , I'm sorry to read that you still had issues. I already opened a PR that will fix the error issue, but about the root cause not so sure about it. I added an increased delay before reading the PlayState.txt to see if that fixes the issue.

In any case, when #127 is merged and a new version released, you should be able to reinstall PlayState without having this issue any longer.
