### ISSUE TITLE
"Total hours" charts adding up play sessions outside month range

### ISSUE THREAD

**Issue by claugaete** [Lacro59/playnite-gameactivity-plugin#207]
I'm on version 3.2, and the "Total hours" charts (on the "Sources", "Genres" and "Tags" tabs) are adding up the playtime for ALL sessions of the games I played that month, not just the sessions that happened during the month in question. For example, in the image below you can see that the chart says I played 377 hours in October, even though I only played around 22. This is because, since installing Playnite, I have played the 5 games you can see on the chart for a collective 377 hours.

![image](https://github.com/Lacro59/playnite-gameactivity-plugin/assets/80221875/d4096b11-9be9-4b0d-9dfe-a5e023a495e8)

This is my first time looking into the plugin's code so this might not be correct, but I think the issue is in the `getActivityByMonth` method in [GameActivityView.xaml.cs](https://github.com/Lacro59/playnite-gameactivity-plugin/blob/40242aadf90576ece8b7f4fb98d2349807cb8d3d/source/Views/GameActivityView.xaml.cs#L336). The method creates a list of `GameActivities` called `listGameActivities`, which contains all games played during a certain month. Each `GameActivities` object contains ALL play sessions for a game, and they are added up in the `for` loops starting in lines 365, 402 and 440 (depending on the type of chart).

The previous version of the plugin had an extra condition (which checked if each session in the `GameActivity` object was in the date range of the month in question), but that condition was removed in the new version, which means all play sessions are added up for all games that were played at least once during the month.

I believe the issue would be solved by adding the following lines just above the `for` loops I previously mentioned:

```
Activities = Activities.Where(y =>
    startOfMonth <= Convert.ToDateTime(y.DateSession).ToLocalTime()
    && Convert.ToDateTime(y.DateSession).ToLocalTime() <= endOfMonth
)
```

This would filter all activities just to the ones that were actually played during the month (according to the player's local timezone). There is probably a more efficient way to do the filtering (this is my first time working with C#), but I hope my reasoning helped. :)

**Comment by Whitechapel-1888** [comment]
I have the same issue. I have one game that I played for about 5000 hours. Per month my playtime averages around 80 to 100 hours.
The aggregation of playtime per month must have some error in it since it literally displays my total playtime for games. So for the aforementioned one, I have 5k hours 7 days into November already.
I assume, that any additional time added to "Time Played" will automatically be added to the monthly playtime, causing the false time display.

Just in case, I checked the json file for that one game id using JSONLint. The file has proper formatting and no syntax errors. The time values seem fine and add up to the monthly value.
